---
name: Data-FormValidator-Constraints-DateTime
version: 1.09
author:
  - Michael Peters <mpeters@plusthree.com>
abstract: D::FV constraints for dates and times
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::FormValidator: 3.61
  DateTime: 0.23
  DateTime::Format::Strptime: 1.00
  Exporter: 0
  perl: 5.6.1
recommends:
  DateTime::Format::MySQL: 0.0301
  DateTime::Format::Pg: 0.050
build_requires:
  DateTime::Format::Builder: 0
provides:
  Data::FormValidator::Constraints::DateTime:
    file: lib/Data/FormValidator/Constraints/DateTime.pm
    version: 1.09
generated_by: Module::Build version 0.2703
